### ISSUE TITLE
Unable to approve or reject workflows in my queue

### ISSUE THREAD

**Issue by anushwhjr** [rupinwhitehatjr/CurriculumWorkflow#1]
Hi Rupin,

I am unable to approve the workflows in my queue.

PFA:
![1](https://user-images.githubusercontent.com/76543458/103052435-29f62780-45bf-11eb-8d44-0fe6bd44e8d3.png)
![2](https://user-images.githubusercontent.com/76543458/103052438-2b275480-45bf-11eb-8c05-f39312f1b7f2.png)

**Comment by anushwhjr** [comment]
Here are two more which I am not able to approve:

https://workflow.whjr.org/viewFlow.html?id=7pjukTbTk5dOjGPpDHWc
https://workflow.whjr.org/viewFlow.html?id=9W5Ns3I8hUH9WmnjkxuE

**Comment by rupinwhitehatjr** [comment]
You can approve or reject only if your email is first in the list of approvers. .
