### ISSUE TITLE
Workflow link does not open properly from email

### ISSUE THREAD

**Issue by aniketshedge-whitehatjr** [rupinwhitehatjr/CurriculumWorkflow#5]
When I open the workflow from the email, it opens the incorrect link. This was the link opened from the email:
https://rupinwhitehatjr.github.io/CurriculumWorkflow/viewFlow.html?id=iqoOdNf1uhiL67aYYw8g

**Comment by rupinwhitehatjr** [comment]
Aniket- URLs have changed recently, can you look at this workflow from the
dashboard?

**Comment by rupinwhitehatjr** [comment]
https://workflow.whjr.org/viewFlow.html?id=iqoOdNf1uhiL67aYYw8g
